#!/usr/bin/bash

# Require sudo password
if ! sudo -v; then
  exit 1
fi

# Colors
GREEN="\033[32m"
BLUE="\033[36m"
RED="\033[31m"

RESET="\033[0m"

# Global Variables
CONFIG_DIR=""
CONFIG_DIR_TO_LINK=""
DOTFILES_DIR=""
DOTFILES_CONFIG=""
D_CONFIG_SUBDIRS=""

COMPUTER_TYPE=""

printf "Beginning install script. You will be prompted to take action during the script process.\n\n"
read -p "Is this a desktop computer (y/n)?" ans
if [[ $ans == "y" ]]; then
  COMPUTER_TYPE="desktop"
else
  COMPUTER_TYPE="laptop"
fi

# Set CONFIG_DIR for symlink purposes later
printf "Searching for .config directory...\n"
CONFIG_DIR=$(find $HOME -maxdepth 1 -name ".config" -type d)
if [[ $CONFIG_DIR ]]; then
  printf "$CONFIG_DIR - ${GREEN}found${RESET}\n"
else
  printf "$HOME/.config - ${RED}not found${RESET}\n"
  read -p "Would you like to create it now (y/n)?" answer
  if [[ $answer != "y" ]]; then
    printf "\n${RED}Exiting script${RESET}. Either create config directory at"
    printf "${BLUE}$HOME/.config${RESET} or let script handle it for you to continue.\n"
    
    exit 0
  else
    printf "Creating config directory at ${BLUE}$HOME/.config${RESET}\n"
    mkdir -p $HOME/.config
    CONFIG_DIR=$(find $HOME -maxdepth 1 -name ".config" -type d)
  fi
fi

# Make sure dotfiles has been cloned in the correct place
printf "\nFinding location of dotfiles directory...\n"
DOTFILES_DIR=$(find $HOME -maxdepth 1 -name "dotfiles" -type d)
if [[ $DOTFILES_DIR ]]; then
  printf "$DOTFILES_DIR - ${GREEN}found${RESET}\n"
else
  printf "$HOME/dotfiles - ${RED}not found${RESET}\n"
  printf "${RED}Exiting script${RESET}. Please make sure to clone dotfiles directory under ${BLUE}$HOME${RESET}\n"
  exit 0
fi

# Make sure dotfiles has .config directory within
DOTFILES_CONFIG=$(find $DOTFILES_DIR -maxdepth 1 -name ".config" -type d)
if [[ $DOTFILES_CONFIG ]]; then
  printf "$DOTFILES_CONFIG - ${GREEN}found${RESET}\n\n"
  D_CONFIG_SUBDIRS=$(find "$DOTFILES_CONFIG" -mindepth 1 -maxdepth 1 -type d)
  printf "Finding directories within ${BLUE}$DOTFILES_CONFIG${RESET}...\n"
  for item in $D_CONFIG_SUBDIRS; do
    printf "$item - ${GREEN}found${RESET}\n"
  done
else
  printf "${RED}Exiting script${RESET}. No ${BLUE}.config${RESET} within ${BLUE}$DOTFILES_DIR${RESET}\n"
  exit 1
fi

printf "\nSearching $CONFIG_DIR for existing directories...\n"
for item in $D_CONFIG_SUBDIRS; do
  if [[ -d "$CONFIG_DIR/${item##*/}" ]]; then
    printf "$CONFIG_DIR/${item##*/} - ${GREEN}found${RESET}\n"
    CONFIG_DIR_TO_LINK+=("$CONFIG_DIR/${item##*/}")
  else
    printf "$CONFIG_DIR/${item##*/} - ${RED}not found${RESET}\n"
    CONFIG_DIR_TO_LINK+=("$CONFIG_DIR/${item##*/}")
  fi
done

printf "\n${RED}Warning${RESET}: The next steps will modify your system by creating directories/symlinks/files
as well as ${BLUE}installing packages${RESET}.\n"
read -p "Are you ready (y/n)?" answer
if [[ $answer != "y" ]]; then
  printf "${RED}Exiting script${RESET}. You may run the script again to pick up where you left off.\n"
  exit 0
else
  printf "${GREEN}Okay${RESET}. Beginning system modifications...\n\n"
fi

if command -v xbps-install >/dev/null 2>&1; then
  sudo xbps-install -Syu
  sudo xbps-install linux-firmware-amd NetworkManager dbus dbus-devel dbus-libs dbus-xll seatd elogind polkit
else
  printf "${RED}Warning${RESET}: command xbps-install not available.\n"
  printf "${RED}Exiting script.${RESET}\n"
  exit 0
fi

printf "${BLUE}BEGINNING SERVICE ACTIVATION...${RESET}\n"
if [[ -d "/etc/sv" ]]; then
  SERVICES=(/etc/sv/*)
  if [[ -d "/var/services" ]]; then
    ACTIVE_SERVICES=(/var/services/*)
    for active_serv in $ACTIVE_SERVICES; do
      for serv in $SERVICES; do
        if [[ ${serv##*/} == ${active_serv##*/} ]]; then
          index=${SERVICES[(ie)$serv]}
          SERVICES[$index]=()
        fi
      done
    done

    for serv in ${SERVICES}; do
      sudo ln -s $serv /var/services/${serv##*/}
      printf "${GREEN}Activated${RESET} service for ${BLUE}$serv${RESET}\n"
    done
  fi
else
  printf "${RED}Warning${RESET}: Cannot find /etc/sv directory.\n"
  printf "${RED}Exiting script.${RESET}\n"
fi

if command -v xbps-install >/dev/null 2>&1; then
  sudo xbps-install mesa-dri zsh sway xdg-user-dirs xdg-desktop-portal xdg-desktop-portal-gtk xdg-desktop-portal-wlr xdg-utils neovim ghostty fastfetch swappy waybar wofi zathura texlive python3 LuaJIT lua54 luarocks-lua54 nodejs pnpm go qt5-wayland firefox xorg-server-xwayland noto-fonts-ttf nerd-fonts-symbols-ttf liberation-fonts-ttf gtk+3 network-manager-applet adwaita-icon-theme pipewire pipewire-pulse pavucontrol libspa-bluetooth alsa-pipewire libjack-pipewire bluez openjdk21-21 openjdk21-jre
fi

printf "\n${BLUE}BEGINNING SYMLINK PROCESS${RESET}\n"
printf "${RED}Warning${RESET}: This process might remove existing config directories to replace them with symlinks.\n"
read -p "Continue (y/n)?" answer
if [[ $answer == "n" ]]; then
  printf "${RED}Exiting script.${RESET}\n"
  exit 0
fi

for dir in $CONFIG_DIR_TO_LINK; do
  if [[ $COMPUTER_TYPE == "desktop" ]]; then
    if [[ -d $dir ]]; then
      rm -rf $dir
      if [[ ${dir##*} == "sway" ]]; then
        sudo ln -s $DOTFILES_CONFIG/${dir##*/}/sway-desktop $dir
      elif [[ ${dir##*} == "waybar" ]]; then
        sudo ln -s $DOTFILES_CONFIG/${dir##*/}/waybar-desktop $dir
      elif [[ ${dir##*} == "fastfetch" ]]; then
        sudo ln -s $DOTFILES_CONFIG/${dir##*/}/fastfetch-desktop $dir
      else
        sudo ln -s $DOTFILES_CONFIG/${dir##*/} $dir
      fi
    else
      if [[ ${dir##*} == "sway" ]]; then
        sudo ln -s $DOTFILES_CONFIG/${dir##*/}/sway-desktop $dir
      elif [[ ${dir##*} == "waybar" ]]; then
        sudo ln -s $DOTFILES_CONFIG/${dir##*/}/waybar-desktop $dir
      elif [[ ${dir##*} == "fastfetch" ]]; then
        sudo ln -s $DOTFILES_CONFIG/${dir##*/}/fastfetch-desktop $dir
      else
        sudo ln -s $DOTFILES_CONFIG/${dir##*/} $dir
      fi
    fi
  elif [[ $COMPUTER_TYPE == "laptop" ]]; then
    if [[ -d $dir ]]; then
      rm -rf $dir
      if [[ ${dir##*} == "sway" ]]; then
        sudo ln -s $DOTFILES_CONFIG/${dir##*/}/sway-desktop $dir
      elif [[ ${dir##*} == "waybar" ]]; then
        sudo ln -s $DOTFILES_CONFIG/${dir##*/}/waybar-desktop $dir
      elif [[ ${dir##*} == "fastfetch" ]]; then
        sudo ln -s $DOTFILES_CONFIG/${dir##*/}/fastfetch-desktop $dir
      else
        sudo ln -s $DOTFILES_CONFIG/${dir##*/} $dir
      fi
    else
      if [[ ${dir##*} == "sway" ]]; then
        sudo ln -s $DOTFILES_CONFIG/${dir##*/}/sway-desktop $dir
      elif [[ ${dir##*} == "waybar" ]]; then
        sudo ln -s $DOTFILES_CONFIG/${dir##*/}/waybar-desktop $dir
      elif [[ ${dir##*} == "fastfetch" ]]; then
        sudo ln -s $DOTFILES_CONFIG/${dir##*/}/fastfetch-desktop $dir
      else
        sudo ln -s $DOTFILES_CONFIG/${dir##*/} $dir
      fi
    fi
  fi
done

if [[ -d "$HOME/Pictures" ]]; then
  if [[ ! -d "$HOME/Pictures/Wallpapers" ]]; then
    sudo ln -s $DOTFILES_DIR/.wallpapers $HOME/Pictures/Wallpapers
  else
    rm -rf $HOME/Pictures/Wallpapers
    sudo ln -s $DOTFILES_DIR/.wallpapers $HOME/Pictures/Wallpapers
  fi
fi

if [[ -d "$HOME/.local/bin" ]]; then
  if [[ ! -d "$HOME/.local/bin/.scripts" ]]; then
    sudo ln -s $DOTFILES_DIR/.scripts $HOME/.local/bin/.scripts
  else
    rm -rf $HOME/.local/bin/.scripts
    sudo ln -s $DOTFILES_DIR/.scripts $HOME/.local/bin/.scripts
  fi
fi

if [[ -d "$HOME/.tmux" ]]; then
  rm -rf .tmux
  sudo ln -s $DOTFILES_DIR/.home/.tmux $HOME/.tmux
else
  sudo ln -s $DOTFILES_DIR/.home/.tmux $HOME/.tmux
fi

if [[ -e "$HOME/.tmux.conf" ]]; then
  rm -rf .tmux.conf
  sudo ln -s $DOTFILES_DIR/.home/.tmux.conf $HOME/.tmux.conf
else
  sudo ln -s $DOTFILES_DIR/.home/.tmux.conf $HOME/.tmux.conf
fi
