#!/usr/bin/zsh

directory="$HOME/Pictures/Wallpapers"

if [[ -d $directory ]]; then
  wallpapers=("$directory"/*)

  index=1
  echo "Choose a background:\n"
  for bg in $wallpapers; do
    printf "\033[36m%d\033[0m: %s\n" $index ${${bg##*/}%.*}
    index=$(($index+1))
  done
  echo ""
  read "answer?Enter the index: "
  if [[ $answer -le $index ]]; then
    (
      swww img $wallpapers[$answer] --transition-fps 144 --transition-type wipe >/dev/null 2>&1 &
    )
  else
    echo "outta bounds"
  fi
fi
