#!/usr/bin/zsh

directory="$HOME/Pictures/Wallpapers"

mon=($(hyprctl monitors | grep Monitor | awk '{print($2)}'))

if [[ $1 -eq 1 ]]; then
  monitor=${mon[1]}
elif [[ $1 -eq 2 ]]; then
  monitor=${mon[2]}
else
  monitor="${mon[1]},${mon[2]}"
fi
  

if [[ -d $directory ]]; then
  wallpapers=("$directory"/*)

  index=1
  echo "Choose a background:\n"
  for bg in $wallpapers; do
    printf "\033[36m%d\033[0m: %s\n" $index ${${bg##*/}%.*}
    index=$(($index+1))
  done
  echo ""
  read "answer?Enter the index: "
  if [[ $answer -le $index ]]; then
    (
      swww img -o $monitor $wallpapers[$answer] --transition-fps 144 --transition-type wipe >/dev/null 2>&1 &
    )
  else
    echo "outta bounds"
  fi
fi
